services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--interval"
      - "30"
      - "--rolling-restart"
      - "--no-pull"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=codingwithkyle@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/letsencrypt
  divinedrop:
    image: codewithkyle/divinedrop:prod
    network_mode: "host"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.divinedrop.rule=Host(`divinedrop.app`)"
      - "traefik.http.routers.divinedrop.entrypoints=websecure"
      - "traefik.http.routers.divinedrop.tls.certresolver=myresolver"
      - "traefik.http.servides.divinedrop.loadbalancer.server.port=3000"
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - .:/app
    env_file: ".env"
    deploy:
      mode: replicated
      replicas: 3
    restart: always
volumes:
  letsencrypt:
