name: Deployment

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@master

            - name: Setup Node and NPM
              uses: actions/setup-node@v1
              with:
                  node-version: 16.14.0

            - name: Install NPM Packages
              run: npm ci

            - name: Install
              run: npm run install:brixi && npm run install:ui

            - name: Compile
              run: npm run production

            - name: Deploy
              run: npm run deploy
              env:
                ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

