name: Build and Deploy

on:
  push:
    branches:
      - release

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'

      - name: Setup Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18.0.0

      - name: Install NPM Packages
        run: npm ci

      - name: Compile
        run: npm run build

      - name: Load SSH Key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy
        run: rsync -azh --delete-after --exclude={'/node_modules','/.git','/.github','/build','/models','/scripts','/styles','/views','.gitignore','brixi.config.js','cssmonster.config.json','go.mod','go.sum','package.json','package-lock.json','server.go','tsconfig.json'} -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/server

